name: Collection Release

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Collection
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          collection_dir: 'ansible_collections/wojtek0806/f5os'
          api_key: "${{ secrets.GALAXY_API_KEY }}"
          publish: false

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "wojtek0806-f5os-${{ github.ref_name }}.tar.gz"
          tag: "${{ github.ref_name }}"
          name: "Release ${{ github.ref_name }}"
          omitBody: true
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Publish Collection
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          collection_dir: 'ansible_collections/wojtek0806/f5os'
          api_key: "${{ secrets.GALAXY_API_KEY }}"
          build: false