name: GitHub Release

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release notes and description.

      - name: Upload Custom Tarball
        uses: actions/upload-artifact@v2
        with:
          name: custom-tarball
          path: https://f5-ansible.s3.amazonaws.com/collections/f5networks-f5_modules-devel.tar.gz
