name: GitHub Release

on:
  push

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Git Describe
        run: |
          git describe --tags --abbrev=0

      - name: Get Latest Tag
        id: get_latest_tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Build Collection
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          collection_dir: 'ansible_collections/wojtek0806/f5os'
          api_key: "${{ secrets.GALAXY_API_KEY }}"
          publish: false

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/wojtek0806-f5os-${{ env.TAG }}.tar.gz"
          tag: "${{ env.TAG }}"
          name: "Release ${{ env.TAG }}"
          omitBody: true
          token: "${{ secrets.TEST_TOKEN }}"

      - name: Publish Collection
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          collection_dir: 'ansible_collections/wojtek0806/f5os'
          api_key: "${{ secrets.GALAXY_API_KEY }}"
          build: false